--- 
title: "Nacimientos en el Atlántico, 2024: condiciones del recién nacido, tipo de parto y atención prenatal"
subtitle: "Análisis exploratorio y pruebas de hipótesis con las Estadísticas Vitales del DANE"
author: ["Brandon Sanchez", "Andres Florez"]
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
site: bookdown::bookdown_site
documentclass: book
lang: es
bibliography: [book.bib, packages.bib]
link-citations: yes
description: "Análisis exploratorio de los nacimientos registrados en el departamento del Atlántico en 2024."
github-repo: bssanchezr7/nacimientos-2024-atl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  fig.align = "center", fig.width = 7, fig.height = 4.5,
  out.width = "85%", dpi = 300
)
library(tidyverse)
source("R/estilo.R")
source("R/tablas.R")
```

```{r write-bib, include=FALSE}
# genera automáticamente la bibliografía de los paquetes de R usados
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
